[phases.setup]
nixPkgs = [
  "python312",
  "ffmpeg",
  "cairo",
  "pango",
  "gdk-pixbuf",
  "glib",
  "libffi",
  "harfbuzz",
  "fontconfig"
]

[phases.build]
cmds = [
  "if [ -d python ]; then cd python && pip install --upgrade pip && pip install -r requirements.txt; fi"
]

[start]
cmd = "cd python && python main.py"
